---
- name: Validate Prometheus configuration
  ansible.builtin.command:
    argv:
      - /usr/local/bin/promtool
      - check
      - config
      - /etc/prometheus/prometheus.yml
  changed_when: false
  listen: Validate and restart Prometheus

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: true
    daemon_reload: true
  listen: Validate and restart Prometheus
